// Command geminipump is a runnable data-pump bot for Codohue whose catalog
// content is generated by the Google Gemini API instead of a fixed dataset.
//
// It bootstraps a namespace through the admin plane (login, upsert config,
// enable catalog auto-embedding), then runs two loops concurrently:
//
//   - a generator loop that periodically asks Gemini for a fresh batch of
//     catalog items (title + summary + category) and ingests them through the
//     data plane, where the embedder worker upserts their dense vectors; and
//   - a pump loop that continuously emits a correlated stream of behavioral
//     events over the generated catalog, so the recommender has a learnable
//     signal rather than uniform noise.
//
// While it runs it periodically reads recommendations and trending back out,
// so you can watch the recommendation loop close as the cron and embedder
// workers process the data it produces.
package main
